### ISSUE TITLE
Need help with the code

### ISSUE THREAD

**Issue by morawi** [rwightman/pytorch-commands#1]
Hi Rwightman,

I was wondering if you could provide me some info on the PyTorch dataloader for the commands data.

Are you transforming the wave files to images?  

I had a go at your dataset.py file, but it was a bit difficult for me to understand the process.

If yes, I was wondering what is your advice to make your dataloader up and running in my code, I have now downloaded the train.7z data. I mean, do I have to change the folders structure? or any thing else?

Thanks in advance,
Rawi

**Comment by rwightman** [comment]
I just noticed this issue while revisiting the code to use parts in another project.

You should be able to just run `train.py /path/to/data/train` ... only sticky point is make sure you specify the train folder and not a folder at a lower level it that contains both train and test data (the dataset traverses paths recursively). I can't remember for sure, but I don't think I made any other changes to the data in train.7z

By default, unless you change arguments, dataset outputs mel-spectrogram images.
